# Generated by Django 3.2.8 on 2021-10-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211011_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='google_docs_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='google_docs_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
