# Generated by Django 3.2.8 on 2021-10-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211011_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
