# Generated by Django 3.2.8 on 2021-10-12 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_video_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 18, 52, 6, 49530)),
        ),
    ]
