# Generated by Django 3.2.8 on 2021-10-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_video_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
