# Generated by Django 3.2.8 on 2021-10-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211014_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='storage',
        ),
    ]
