# Generated by Django 3.2.8 on 2021-10-14 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('github', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField()),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='YTVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('video_id', models.CharField(max_length=30)),
                ('is_done', models.BooleanField(default=False)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.playlist')),
            ],
        ),
    ]
